ACCEPT PROMT_UNIVERSITY_ID CHAR PROMPT 'Введите идентификатор университета: ';

CREATE TABLE TASK_3_RESULT (
  UNIV_ID INTEGER PRIMARY KEY,
  STUDENTS_COUNT INTEGER,
  CALL_COUNT INTEGER
);

CREATE OR REPLACE PACKAGE UNIVERSITY_PACKAGE AS
  FUNCTION STUDENTS_COUNT(
    UNIVERSITY_ID IN NUMBER
  ) RETURN NUMBER;

  PROCEDURE INSERT_TO_TABLE;
END;
/

CREATE OR REPLACE PACKAGE BODY UNIVERSITY_PACKAGE AS
  CALL_COUNT          INTEGER := 0;
  LAST_UNIVERSITY_ID  NUMBER;
  LAST_STUDENTS_COUNT NUMBER;

  FUNCTION STUDENTS_COUNT(
    UNIVERSITY_ID IN NUMBER
  ) RETURN NUMBER IS
    RES NUMBER;
  BEGIN
    CALL_COUNT := CALL_COUNT + 1;
    LAST_UNIVERSITY_ID := UNIVERSITY_ID;

    SELECT
      COUNT(*) INTO RES
    FROM
      STUDENT
    WHERE
      STUDENT.UNIV_ID = UNIVERSITY_ID;

    LAST_STUDENTS_COUNT := RES;
    RETURN RES;
  END;

  PROCEDURE INSERT_TO_TABLE IS
  BEGIN
    INSERT INTO TASK_3_RESULT VALUES (
      LAST_UNIVERSITY_ID,
      LAST_STUDENTS_COUNT,
      CALL_COUNT
    );
  END;
END;
/

DECLARE
  STUDENTS_COUNT NUMBER;

BEGIN
  STUDENTS_COUNT := UNIVERSITY_PACKAGE.STUDENTS_COUNT('&promt_university_id');
  UNIVERSITY_PACKAGE.INSERT_TO_TABLE();
END;
/