DECLARE
  U_ID               UNIVERSITY.UNIV_ID%TYPE;
  U_NAME             UNIVERSITY.UNIV_NAME%TYPE;
  U_RATING           UNIVERSITY.RATING%TYPE;
  U_CITY             UNIVERSITY.CITY%TYPE;

  CURSOR UW_RATING_G_400 IS
    SELECT
      *
    FROM
      UNIVERSITY
    WHERE
      RATING > 400;

  U_RATING_EXCEPTION EXCEPTION;

BEGIN
  OPEN UW_RATING_G_400;

  FETCH UW_RATING_G_400 INTO U_ID, U_NAME, U_RATING, U_CITY;

  WHILE UW_RATING_G_400%FOUND LOOP
    BEGIN
      IF U_CITY <> 'ÂÎÐÎÍÅÆ' THEN
        RAISE U_RATING_EXCEPTION;
      END IF;

      FETCH UW_RATING_G_400 INTO U_ID, U_NAME, U_RATING, U_CITY;
    EXCEPTION
      WHEN U_RATING_EXCEPTION THEN
        DBMS_OUTPUT.PUT_LINE(U_NAME
          ||' '
          ||U_RATING
          ||' '
          ||U_CITY);
        FETCH UW_RATING_G_400 INTO U_ID, U_NAME, U_RATING, U_CITY;
    END;
  END LOOP;
END;
/