ACCEPT PROMT_STUDENT_ID NUMBER PROMPT 'Введите идентификатор студента: ';
ACCEPT PROMT_SUBJECT_ID NUMBER PROMPT 'Введите идентификатор предмета: ';
ACCEPT EXAM_MARK NUMBER PROMPT 'Введите оценку за экзамен: ';

CREATE TABLE TASK_4_RESULT (
    ATTEMP_ID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
    STUD_ID INTEGER REFERENCES STUDENT(STUD_ID),
    OLD_AVERAGE INTEGER,
    NEW_AVERAGE INTEGER
);

CREATE OR REPLACE TRIGGER AVERAGE_SCORE BEFORE
    INSERT ON EXAMS FOR EACH ROW

DECLARE
    EVASION       CONSTANT FLOAT := 1.0;
    OLD_AVERAGE   INTEGER;
    NEW_AVERAGE   INTEGER;
    AVG_EXCEPTION EXCEPTION;
    PRAGMA EXCEPTION_INIT (AVG_EXCEPTION, -20001);
    PRAGMA AUTONOMOUS_TRANSACTION;

BEGIN
    SELECT
        AVG(EXAMS.MARK), (SUM(EXAMS.MARK) + :NEW.MARK) / (COUNT(EXAMS.MARK) + 1) INTO OLD_AVERAGE, NEW_AVERAGE
    FROM
        EXAMS
    WHERE
        EXAMS.STUD_ID = :NEW.STUD_ID;

    IF ABS(OLD_AVERAGE - NEW_AVERAGE) >= EVASION THEN
        INSERT INTO TASK_4_RESULT (
            STUD_ID,
            OLD_AVERAGE,
            NEW_AVERAGE
        ) VALUES (
            :NEW.STUD_ID,
            OLD_AVERAGE,
            NEW_AVERAGE
        );

        COMMIT;

        RAISE_APPLICATION_ERROR(-20001, 'Средний балл превосходит значение максимального отклонения "'
            ||EVASION
            ||'".');
    END IF;
END;
/

DECLARE
    NEXT_EXAM_ID NUMBER;

BEGIN
    SELECT
        MAX(EXAMS.EXAM_ID) + 1 INTO NEXT_EXAM_ID
    FROM
        EXAMS;

    INSERT INTO EXAMS VALUES (
        NEXT_EXAM_ID,
        &PROMT_STUDENT_ID,
        &PROMT_SUBJECT_ID,
        &EXAM_MARK,
        CURRENT_DATE
    );
END;
/