ACCEPT PROMT_STUDENT_SURNAME CHAR PROMPT 'Введите фамилию студента: ';

DECLARE
  GRADES_SUM NUMBER;

  FUNCTION SUM_OF_GRADES_BY_SUBJECT(
    STUDENT_SURNAME IN CHAR
  ) RETURN NUMBER IS
    GRADES_SUM NUMBER;
  BEGIN
    SELECT
      SUM(EXAMS.MARK) INTO GRADES_SUM
    FROM
      EXAMS
    WHERE
      EXAMS.STUD_ID IN (
        SELECT
          STUDENT.STUD_ID
        FROM
          STUDENT
        WHERE
          STUDENT.SURNAME = STUDENT_SURNAME
      );
    RETURN GRADES_SUM;
  END;

BEGIN
  GRADES_SUM := SUM_OF_GRADES_BY_SUBJECT('&PROMT_STUDENT_SURNAME');
  DBMS_OUTPUT.PUT_LINE('Сумма оценок по предметам: '
    ||GRADES_SUM);
END;
/