-- Connect to XEPDB1 as ME
--
CONN ME/Passw0rd@XEPDB1

-- Create tables
--
CREATE TABLE UNIVERSITY (
  UNIV_ID INTEGER PRIMARY KEY,
  UNIV_NAME CHAR(140) NOT NULL UNIQUE,
  RATING INTEGER,
  CITY CHAR(30) NOT NULL
);

CREATE TABLE SUBJECT (
  SUBJ_ID INTEGER PRIMARY KEY,
  SUBJ_NAME CHAR(50) NOT NULL,
  HOUR INTEGER,
  SEMESTR INTEGER
);

CREATE TABLE LECTURER (
  LECTURER_ID INTEGER PRIMARY KEY,
  SURNAME CHAR(30) NOT NULL,
  NAME CHAR(30) NOT NULL,
  CITY CHAR(30) NOT NULL,
  UNIV_ID INTEGER REFERENCES UNIVERSITY(UNIV_ID)
);

CREATE TABLE SUBJ_LECT (
  LECTURER_ID INTEGER REFERENCES LECTURER(LECTURER_ID),
  SUBJ_ID INTEGER REFERENCES SUBJECT(SUBJ_ID)
);

CREATE TABLE STUDENT (
  STUD_ID INTEGER PRIMARY KEY,
  SURNAME CHAR(30) NOT NULL,
  NAME CHAR(30) NOT NULL,
  STIPEND INTEGER,
  KURS INTEGER NOT NULL,
  CITY CHAR(30) NOT NULL,
  BIRTHDAY DATE,
  UNIV_ID INTEGER REFERENCES UNIVERSITY(UNIV_ID)
);

CREATE TABLE EXAMS (
  EXAM_ID INTEGER PRIMARY KEY,
  STUD_ID INTEGER REFERENCES STUDENT(STUD_ID),
  SUBJ_ID INTEGER REFERENCES SUBJECT(SUBJ_ID),
  MARK INTEGER,
  EXAM_DATE DATE,
  CHECK ((MARK>=2) AND (MARK<=5))
);